import { StyleSheet } from 'react-native';
import { Layout } from './Layout';
import { Colors } from './Colors';

export const styles = StyleSheet.create({
  title: {
    alignSelf: 'flex-end',
    textAlign: 'right',
    fontWeight: '400',
    fontSize: 24,
    lineHeight: 36,
    color: Colors.text,
    marginBottom: 12,
    marginRight: 24,
  },
  subtitle: {
    alignSelf: 'flex-end',
    fontWeight: '200',
    fontSize: 18,
    lineHeight: 27,
    textAlign: 'right',
    color: Colors.text,
    marginLeft: 20,
  },
  page: {
    backgroundColor: Colors.background,
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginBottom: 50,
  },
  modal: {
    backgroundColor: Colors.modalBackground,
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  modalHeader: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalTitle: {
    flexGrow: 1,
    fontWeight: '400',
    fontSize: 36,
    lineHeight: 54,
    color: Colors.text_negative,
  },
  modalSubminButton: {
    width: 205,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.modalSubmitButton,
    borderRadius: 15,
    marginTop: 40,
  },
  modalSubminButtonText: {
    fontSize: 28,
    lineHeight: 54,
    fontWeight: 'normal',
    color: Colors.text_negative,
  },
  modalInput: {
    width: '60%',
    height: 40,
    color: Colors.text_negative,
    borderColor: Colors.modalBackground,
    borderWidth: 1,
    borderBottomColor: Colors.modalInputBorder,
  },
});
